### ISSUE TITLE
Could you give a general introduction for different methods?

### ISSUE THREAD

**Issue by serre20** [Axect/Noisy_Regression#1]
You have collected many methods for noisy regression, which is a really excellent work!
Could you give a general introduction for different methods? 
What is more, it will be great if comparisons between different methods are presented.

**Comment by Axect** [comment]
Thank you for your interest in the GitHub repository and for recognizing the effort put into collecting methods for noisy regression. I appreciate your kind words!

In fact, this GitHub repository was created as part of the preparation for my presentation. You can find the details of the presentation content through the following link: [MITP2023 Review](https://www.dropbox.com/scl/fi/k0kad044vwolwinxr50zz/Review_MITP2023_TG_Kim.pdf?rlkey=7vd4bd8jj71oyp212tivbjvd1&dl=0)

Following your suggestion, I will add the link to the presentation material in the README to make it easier for others to access and understand the context and comparisons between different noisy regression methods.

Thank you again for your suggestion, and I hope you find the presentation material informative and helpful.

**Comment by serre20** [comment]
Thanks for your help!
